version: '3.8'

services:
  api-mongo:
    build: .
    container_name: sagas-api-mongo
    ports:
      - "4001:3000"
    environment:
      - NODE_ENV=production
      - CIRCUIT_BREAKER_FAILURE_RATE=0.3
      - MONGODB_URI=mongodb://mongoadmin:secret@mongo:27017/your-db-name?authSource=admin
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - DLQ_BACKEND=mongo
    depends_on:
      - mongo
    restart: unless-stopped

  api-rabbitmq:
    build: .
    container_name: sagas-api-rabbitmq
    ports:
      - "4002:3000"
    environment:
      - NODE_ENV=production
      - CIRCUIT_BREAKER_FAILURE_RATE=0.5
      - MONGODB_URI=mongodb://mongoadmin:secret@mongo:27017/your-db-name?authSource=admin
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - DLQ_BACKEND=rabbitmq
    depends_on:
      - rabbitmq
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4.1-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    restart: unless-stopped

